/**
 * Every threshold that decides a number, on screen and adjustable (D20, D31,
 * D55, and the standing constraint that no magic number is buried in code).
 *
 * The rows are generated by walking `parameterPaths()`, never from a list kept
 * here: a parameter added to the contract appears in this panel by existing,
 * and cannot be forgotten. Each row carries its unit, its default, the
 * definition sentence from `PARAMETER_DEFINITIONS` verbatim and the decision
 * the default comes from, so the meaning of a threshold is one disclosure away
 * from the control that changes it.
 *
 * One block is shown but not edited here:
 *
 * - **Tracking (D6).** The automatic layer is keyed by the hash of the tracking
 *   parameters (D51). Editing one from this panel would orphan the tracking
 *   pass that produced the track underneath, and `derive()` cannot act on it in
 *   any case — the values would change nothing until the video were tracked
 *   again. They are shown with their definitions and a pointer to the Track
 *   step, and passed through untouched in every emitted `Parameters`.
 *
 * The trial-censoring, strategy-rule and quality-tier thresholds D55 moved into
 * `Parameters` are ordinary editable blocks here, like every other threshold
 * that decides a number: they are hashed and exported, so nothing about them
 * needs a caveat any more.
 *
 * A change is emitted only when the whole parameter set validates. Invalid
 * input keeps what the user typed, says what is wrong beside the row that is
 * wrong, and emits nothing: a half-typed threshold must not re-derive the
 * trial.
 */
import {
  DEFAULT_PARAMETERS,
  PARAMETER_DECISIONS,
  PARAMETER_DEFINITIONS,
  PARAMETER_UNITS,
  parameterAt,
  parameterPaths,
  validateParameters,
  type ParameterPath,
} from '../../analysis/parameters.js';
import type { DerivedAnalysis } from '../../analysis/derive.js';
import { clampToBound } from '../../analysis/tracker/params.js';
import type { Parameters } from '../../contracts/parameters.js';
import { append, button, disclosure, el, uniqueId } from '../dom.js';
import { ANALYSIS_PARAMETER_BOUNDS, hasSlider } from './analysis-parameter-bounds.js';
import { describeDiff } from './describe-diff.js';
import { formatParameterValue } from './format.js';
import type { AnnounceCallback, Component } from './types.js';

export interface ParametersPanelProps {
  parameters: Parameters;
  /** The analysis before the last change and the one after it, for the badge (D20). */
  previous?: DerivedAnalysis | null;
  next?: DerivedAnalysis | null;
}

export interface ParametersPanelCallbacks extends AnnounceCallback {
  onParametersChange(next: Parameters): void;
}

/** How long the panel waits after the last keystroke or drag before re-deriving. */
export const CHANGE_DEBOUNCE_MS = 100;

const BLOCK_LABELS: Record<string, string> = {
  holeInvestigation: 'Hole investigation',
  escapeEntry: 'Escape-box entry',
  trialCutoff_s: 'Trial cutoff',
  targetQuadrant: 'Target quadrant',
  kinematicsSmoothingWindowFrames: 'Path smoothing',
  gapFilling: 'Gap filling',
  kinematics: 'Frame timing',
  noseConfidenceCutoff: 'Nose confidence',
  outlierVelocityThreshold_cmPerS: 'Outlier rejection',
  trialCensoring: 'Trial censoring',
  strategy: 'Search strategy',
  quality: 'Quality tier',
  tracking: 'Tracking',
};

const TRACKING_NOTE =
  'These are set on the Track step. Changing one needs a new tracking pass — the automatic track is keyed by their hash (D51) — so they are shown here for reference and cannot be edited from this step.';

/** The top-level block a leaf path belongs to. */
function blockOf(path: ParameterPath): string {
  return path.split('.')[0]!;
}

/**
 * A control label from the path itself, so a new parameter needs no entry in a
 * table here. Unit suffixes are dropped because the unit is shown in its own
 * column: `outlierVelocityThreshold_cmPerS` reads "Outlier velocity threshold".
 */
export function labelForPath(path: ParameterPath): string {
  const leaf = path.split('.').pop()!;
  const withoutUnit = leaf.replace(/_(s|cm|cm2|cmPerS|px|deg)$/, '');
  const words = withoutUnit.replace(/([a-z0-9])([A-Z])/g, '$1 $2').toLowerCase();
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/**
 * Each validation problem attached to the row it belongs to. `validateParameters`
 * returns sentences that begin with a dotted path, and some of those paths are
 * deeper than a leaf (`tracking.threshold.manualValue`) or indexed
 * (`tracking.backgroundExcludeRanges[0]`), so the longest leaf that prefixes the
 * message wins.
 */
export function problemsByPath(
  problems: readonly string[],
  paths: readonly ParameterPath[],
): Map<ParameterPath, string[]> {
  const byPath = new Map<ParameterPath, string[]>();
  const longestFirst = [...paths].sort((a, b) => b.length - a.length);
  for (const problem of problems) {
    // A message may name the leaf itself (`trialCutoff_s must …`), a field
    // inside it (`tracking.threshold.manualValue must …`) or an element of it
    // (`tracking.backgroundExcludeRanges[0] must …`).
    const owner = longestFirst.find(
      (path) =>
        problem === path ||
        problem.startsWith(`${path} `) ||
        problem.startsWith(`${path}.`) ||
        problem.startsWith(`${path}[`),
    );
    if (!owner) continue;
    const list = byPath.get(owner) ?? [];
    list.push(problem);
    byPath.set(owner, list);
  }
  return byPath;
}

/** A deep copy of a parameter set, so editing the panel never mutates its props. */
function clone(parameters: Parameters): Parameters {
  return structuredClone(parameters);
}

function setAt(parameters: Parameters, path: ParameterPath, value: unknown): void {
  const keys = path.split('.');
  let target = parameters as unknown as Record<string, unknown>;
  for (const key of keys.slice(0, -1)) {
    target = target[key] as Record<string, unknown>;
  }
  target[keys[keys.length - 1]!] = value;
}

/**
 * Paint one row's validation state. The message is linked to the control with
 * `aria-describedby` and the control marked `aria-invalid`, so a user tabbing
 * back to the field is told it is the bad one rather than having to find it in
 * the summary at the top (D37).
 */
function markRow(row: Row, messages: readonly string[]): void {
  const bad = messages.length > 0;
  row.error.textContent = messages.join(' ');
  row.error.hidden = !bad;
  row.element.classList.toggle('is-invalid', bad);
  for (const control of row.element.querySelectorAll('input, select, textarea')) {
    // The slider already has an `aria-describedby` of its own — it points at the
    // numeric field it is a twin of — so the error id is added to and removed
    // from the list rather than replacing it. Overwriting left a recovered
    // slider with no description at all, which is the state it spends most of
    // its life in.
    const described = new Set(
      (control.getAttribute('aria-describedby') ?? '').split(/\s+/).filter(Boolean),
    );
    if (bad) {
      control.setAttribute('aria-invalid', 'true');
      described.add(row.error.id);
    } else {
      control.removeAttribute('aria-invalid');
      described.delete(row.error.id);
    }
    if (described.size > 0) control.setAttribute('aria-describedby', [...described].join(' '));
    else control.removeAttribute('aria-describedby');
  }
}

interface Row {
  path: ParameterPath;
  element: HTMLElement;
  error: HTMLElement;
  /** Writes the current working value into the controls. */
  sync(): void;
  /** Whether the user is in one of this row's controls right now. */
  hasFocus(): boolean;
}

export function createParametersPanel(
  container: HTMLElement,
  props: ParametersPanelProps,
  callbacks: ParametersPanelCallbacks,
): Component<ParametersPanelProps> {
  let current = props;
  let working = clone(props.parameters);
  let timer: ReturnType<typeof setTimeout> | null = null;

  const paths = parameterPaths(working);
  const rows: Row[] = [];

  const root = el('section', { class: 'parameters-panel' });
  const headingId = uniqueId('parameters-heading');
  root.setAttribute('aria-labelledby', headingId);
  root.append(
    el('h3', { id: headingId, text: 'Parameters' }),
    el('p', {
      class: 'what',
      text: 'Every threshold that decides a number. Change one and the events, metrics and quality report are recomputed from the same track — nothing is patched, everything is re-derived (D20).',
    }),
  );

  const badge = el('output', { class: 'diff-badge', attrs: { role: 'status' } });
  const summary = el('p', { class: 'error', attrs: { role: 'alert', hidden: true } });
  root.append(badge, summary);

  function announce(message: string): void {
    callbacks.onAnnounce?.(message);
  }

  /** Validate, paint the errors, and emit only if the whole set is legal. */
  function commit(reason: string): void {
    const problems = validateParameters(working);
    const byPath = problemsByPath(problems, paths);

    for (const row of rows) markRow(row, byPath.get(row.path) ?? []);

    if (problems.length > 0) {
      // Unhidden first: a live region written to while `display: none` is not
      // announced by every screen reader.
      summary.hidden = false;
      summary.textContent = `${problems.length} parameter${problems.length === 1 ? '' : 's'} out of range; nothing has been recomputed. ${problems.join('; ')}`;
      if (timer !== null) {
        clearTimeout(timer);
        timer = null;
      }
      return;
    }

    summary.hidden = true;
    summary.textContent = '';

    if (timer !== null) clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      callbacks.onParametersChange(clone(working));
      announce(reason);
    }, CHANGE_DEBOUNCE_MS);
  }

  /** A number row: a slider and the numeric field that is its twin. */
  function numberRow(path: ParameterPath): Row {
    const bound = hasSlider(path) ? ANALYSIS_PARAMETER_BOUNDS[path] : null;
    const label = labelForPath(path);
    const numberInput = el('input', { id: uniqueId('param'), class: 'number-input' });
    numberInput.type = 'number';
    if (bound) numberInput.step = bound.step;

    const slider = el('input', { id: uniqueId('param-slider'), class: 'param-slider' });
    slider.type = 'range';
    if (bound) {
      slider.min = String(bound.min);
      slider.max = String(bound.max);
      slider.step = bound.step;
    }
    // The numeric field carries the row's label; the slider is the same value
    // reached another way, and says so rather than repeating a bare label.
    slider.setAttribute('aria-label', `${label} slider`);
    slider.setAttribute('aria-describedby', numberInput.id);

    const error = el('p', {
      id: uniqueId('param-error'),
      class: 'error param-error',
      attrs: { hidden: true },
    });
    const definition = disclosure('Definition', [
      el('p', { text: PARAMETER_DEFINITIONS[path] }),
      el('p', {
        class: 'param-decision',
        text: `Default ${formatParameterValue(parameterAt(DEFAULT_PARAMETERS, path))} · decision ${PARAMETER_DECISIONS[path] || 'not recorded'}`,
      }),
      bound && el('p', { class: 'param-decision', text: `Slider range: ${bound.reason}` }),
    ]);

    function write(value: number): void {
      setAt(working, path, value);
      if (document.activeElement !== slider) slider.value = String(value);
      if (document.activeElement !== numberInput) numberInput.value = String(value);
    }

    numberInput.addEventListener('input', () => {
      const typed = Number(numberInput.value);
      if (numberInput.value.trim() === '' || !Number.isFinite(typed)) {
        // Keep what was typed; `validateParameters` will name the problem.
        setAt(working, path, Number.NaN);
        commit(`${label} needs a number.`);
        return;
      }
      setAt(working, path, typed);
      // The slider clamps for display; the typed value stands, because a lab
      // that needs a threshold past the end of the track may have one.
      if (bound) slider.value = String(clampToBound(typed, bound));
      commit(`${label} set to ${typed}.`);
    });

    slider.addEventListener('input', () => {
      const value = Number(slider.value);
      write(value);
      numberInput.value = String(value);
      commit(`${label} set to ${value}.`);
    });

    const element = el('div', { class: 'param-row' }, [
      el('label', { text: label, attrs: { for: numberInput.id } }),
      el('div', { class: 'param-controls' }, [
        slider,
        numberInput,
        el('span', { class: 'param-unit', text: PARAMETER_UNITS[path] }),
      ]),
      error,
      definition,
    ]);

    return {
      path,
      element,
      error,
      sync() {
        const value = parameterAt(working, path);
        if (typeof value !== 'number') return;
        write(value);
      },
      hasFocus: () => document.activeElement === numberInput || document.activeElement === slider,
    };
  }

  /**
   * The two booleans: `gapFilling.enabled` and, since D55,
   * `trialCensoring.censorToCutoff`. A switch has no slider.
   */
  function booleanRow(path: ParameterPath): Row {
    const label = labelForPath(path);
    const input = el('input', { id: uniqueId('param'), class: 'param-checkbox' });
    input.type = 'checkbox';
    const error = el('p', {
      id: uniqueId('param-error'),
      class: 'error param-error',
      attrs: { hidden: true },
    });

    input.addEventListener('change', () => {
      setAt(working, path, input.checked);
      commit(`${label} turned ${input.checked ? 'on' : 'off'}.`);
    });

    const element = el('div', { class: 'param-row' }, [
      el('div', { class: 'param-switch' }, [
        input,
        el('label', { text: label, attrs: { for: input.id } }),
        el('span', { class: 'param-unit', text: PARAMETER_UNITS[path] }),
      ]),
      error,
      disclosure('Definition', [
        el('p', { text: PARAMETER_DEFINITIONS[path] }),
        el('p', {
          class: 'param-decision',
          text: `Default ${formatParameterValue(parameterAt(DEFAULT_PARAMETERS, path))} · decision ${PARAMETER_DECISIONS[path] || 'not recorded'}`,
        }),
      ]),
    ]);

    return {
      path,
      element,
      error,
      sync() {
        if (document.activeElement === input) return;
        input.checked = parameterAt(working, path) === true;
      },
      hasFocus: () => document.activeElement === input,
    };
  }

  /** A tracking parameter: shown in full, edited on the Track step. */
  function readOnlyRow(path: ParameterPath): Row {
    const value = el('span', { class: 'param-readonly-value' });
    const error = el('p', {
      id: uniqueId('param-error'),
      class: 'error param-error',
      attrs: { hidden: true },
    });
    const element = el('div', { class: 'param-row is-readonly' }, [
      el('div', { class: 'param-controls' }, [
        el('span', { class: 'label-like', text: labelForPath(path) }),
        value,
        el('span', { class: 'param-unit', text: PARAMETER_UNITS[path] }),
      ]),
      error,
      disclosure('Definition', [
        el('p', { text: PARAMETER_DEFINITIONS[path] }),
        el('p', {
          class: 'param-decision',
          text: `Default ${formatParameterValue(parameterAt(DEFAULT_PARAMETERS, path))} · decision ${PARAMETER_DECISIONS[path] || 'not recorded'}`,
        }),
      ]),
    ]);

    return {
      path,
      element,
      error,
      sync() {
        value.textContent = formatParameterValue(parameterAt(working, path));
      },
      // Nothing in a read-only row can hold focus.
      hasFocus: () => false,
    };
  }

  function rowFor(path: ParameterPath): Row {
    if (blockOf(path) === 'tracking') return readOnlyRow(path);
    if (typeof parameterAt(DEFAULT_PARAMETERS, path) === 'boolean') return booleanRow(path);
    return numberRow(path);
  }

  /** One fieldset per top-level block, in the contract's own order. */
  function buildBlocks(): HTMLElement[] {
    const order: string[] = [];
    const grouped = new Map<string, ParameterPath[]>();
    for (const path of paths) {
      const block = blockOf(path);
      if (!grouped.has(block)) {
        grouped.set(block, []);
        order.push(block);
      }
      grouped.get(block)!.push(path);
    }

    return order.map((block) => {
      const blockPaths = grouped.get(block)!;
      const readOnly = block === 'tracking';
      const decision = PARAMETER_DECISIONS[blockPaths[0]!];
      const fieldset = el('fieldset', { class: 'param-block' });
      const legend = el('legend', {
        text: `${BLOCK_LABELS[block] ?? labelForPath(blockPaths[0]!)}${decision ? ` (${decision})` : ''}`,
      });
      fieldset.append(legend);

      if (readOnly) {
        fieldset.classList.add('is-readonly');
        fieldset.append(el('p', { class: 'hint', text: TRACKING_NOTE }));
      } else {
        fieldset.append(
          button(
            'Reset block to defaults',
            () => {
              for (const path of blockPaths) {
                setAt(working, path, structuredClone(parameterAt(DEFAULT_PARAMETERS, path)));
              }
              for (const row of rows) row.sync();
              commit(`${BLOCK_LABELS[block] ?? block} reset to defaults.`);
            },
            { class: 'reset-block' },
          ),
        );
      }

      for (const path of blockPaths) {
        const row = rowFor(path);
        rows.push(row);
        fieldset.append(row.element);
      }
      return fieldset;
    });
  }

  append(root, buildBlocks());

  container.append(root);

  function render(): void {
    for (const row of rows) row.sync();
    badge.textContent = describeDiff(current.previous, current.next);
  }

  render();
  commitInitialValidation();

  /** Paint any problem the incoming parameters already have, without emitting. */
  function commitInitialValidation(): void {
    const byPath = problemsByPath(validateParameters(working), paths);
    for (const row of rows) markRow(row, byPath.get(row.path) ?? []);
  }

  return {
    update(nextProps) {
      current = nextProps;
      // Incoming parameters replace the working set — except for a row the user
      // currently has focus in. `write()` already refuses to repaint a focused
      // control, so overwriting its working value here would leave the panel
      // showing one number and emitting another: the user's 240 on screen, the
      // props' 180 in the next commit. The displayed value is the working value
      // for exactly the row being edited, and the props win everywhere else.
      const focused = rows.find((row) => row.hasFocus());
      const keep = focused ? structuredClone(parameterAt(working, focused.path)) : undefined;
      // A queued edit belongs to the parameters it was typed against. Once new
      // ones arrive it must not fire — it would emit a value the user set for a
      // different trial, and announce it as if they had just typed it here.
      if (timer !== null) {
        clearTimeout(timer);
        timer = null;
      }
      working = clone(nextProps.parameters);
      if (focused && keep !== undefined) setAt(working, focused.path, keep);
      render();
      commitInitialValidation();
    },
    destroy() {
      if (timer !== null) clearTimeout(timer);
      timer = null;
      // Only this panel's own nodes: the container may hold a heading, or a
      // second panel, that this component did not create (see `Component`).
      root.remove();
    },
  };
}

/** The analysis paths this panel edits, for the tests and the harness. */
export function editableParameterPaths(parameters: Parameters): ParameterPath[] {
  return parameterPaths(parameters).filter((path) => blockOf(path) !== 'tracking');
}
